#! /bin/bash

## remember you have to clone the contfrac repo

cp contfrac/inst/example_article_contfrac.Rnw .
cp contfrac/vignettes/contfrac.bib .
cp contfrac/man/figures/contfrac.png .
R CMD Sweave example_article_contfrac.Rnw
pdflatex example_article_contfrac
bibtex example_article_contfrac
pdflatex example_article_contfrac
pdflatex example_article_contfrac

