#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/crinkled_arc/example_article_crinkled_arc.Rnw .
cp ${base_dir}/crinkled_arc/crinkled.bib .
R CMD Sweave example_article_crinkled_arc.Rnw
latexmk -pdf example_article_crinkled_arc.tex

