#! /bin/bash

## remember you have to execute submod once

cp ./elliptic/vignettes/residuetheorem.Rnw ./residuetheorem.Rnw
cp ./elliptic/vignettes/elliptic.bib .
./tragularize residuetheorem.Rnw 
R CMD Sweave example_article_residuetheorem.Rnw
pdflatex example_article_residuetheorem
bibtex example_article_residuetheorem
pdflatex example_article_residuetheorem
pdflatex example_article_residuetheorem
