#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/rstudio/elliptic/vignettes/residuetheorem.Rnw ./residuetheorem.Rnw
cp ${base_dir}/elliptic/vignettes/elliptic.bib .

./tragularize residuetheorem.Rnw 
R CMD Sweave example_article_residuetheorem.Rnw
pdflatex example_article_residuetheorem
bibtex example_article_residuetheorem
pdflatex example_article_residuetheorem
pdflatex example_article_residuetheorem
