#! /bin/bash

## remember you have to execute submod once

cp ./evitaicossa/inst/evitaicossa.Rnw .
cp ./evitaicossa/ins/evitaicossa.bib .
cp ./evitaicossa/man/figures/evitaicossa.png .
./tragularize evitaicossa.Rnw 
R CMD Sweave example_article_evitaicossa.Rnw
pdflatex example_article_evitaicossa
bibtex example_article_evitaicossa
pdflatex example_article_evitaicossa
pdflatex example_article_evitaicossa

