#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/evitaicossa/inst/evitaicossa_tragula.Rnw ./evitaicossa.Rnw
cp ${base_dir}/evitaicossa/inst/evitaicossa.bib .
cp ${base_dir}/evitaicossa/man/figures/evitaicossa.png .

./tragularize evitaicossa.Rnw 
R CMD Sweave example_article_evitaicossa.Rnw
latexmk -pdf example_article_evitaicossa.tex
