#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/evitaicossa/inst/evitaicossa_tragula.Rnw ${base_dir}/evitaicossa.Rnw
cp ${base_dir}/evitaicossa/inst/evitaicossa.bib .
cp ${base_dir}/evitaicossa/man/figures/evitaicossa.png .

./tragularize evitaicossa.Rnw 
R CMD Sweave example_article_evitaicossa.Rnw
pdflatex example_article_evitaicossa
bibtex example_article_evitaicossa
pdflatex example_article_evitaicossa
pdflatex example_article_evitaicossa

