#! /bin/bash

## remember you have to execute submod once

cp freegroup/vignettes/* .
./tragularize freegroup.Rnw 
R CMD Sweave example_article_freegroup.Rnw
pdflatex example_article_freegroup
bibtex example_article_freegroup
pdflatex example_article_freegroup
pdflatex example_article_freegroup

