#! /bin/bash

## No need to execute tragularize here as guidelines.Rnw is not a package vignette (cf permmaker)

R CMD Sweave guidelines.Rnw
pdflatex guidelines
bibtex guidelines
pdflatex guidelines
pdflatex guidelines


