#! /bin/bash

## remember you have to execute submod once

cp knotR/vignettes/* .
./tragularize knot.Rnw 
R CMD Sweave example_article_knot.Rnw
pdflatex example_article_knot
bibtex example_article_knot
pdflatex example_article_knot
pdflatex example_article_knot




