#! /bin/bash

## remember you have to execute submod once

cp knotR/vignettes/* .
./tragularize knotR.Rnw 
R CMD Sweave example_article_knotR.Rnw
pdflatex example_article_knotR
bibtex example_article_knotR
pdflatex example_article_knotR
pdflatex example_article_knotR




