#!/bin/bash


## see README.md

cp knotR/vignettes/* .
cat knot.Rnw |sed -e s/nojss/article/ |sed -e s/jss/tragula/ > example_article_knot.Rnw
R CMD Sweave example_article_knot.Rnw
pdflatex example_article_knot
bibtex example_article_knot
pdflatex example_article_knot
pdflatex example_article_knot




