#! /bin/bash

## remember you have to execute submod once

cp lorentz/vignettes/* .
./tragularize lorentz.Rnw 
R CMD Sweave example_article_lorentz.Rnw
pdflatex example_article_lorentz
bibtex example_article_lorentz
pdflatex example_article_lorentz
pdflatex example_article_lorentz

