#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/permutations/vignettes/* .
./tragularize permutations.Rnw 
R CMD Sweave example_article_permutations.Rnw
pdflatex example_article_permutations
bibtex example_article_permutations
pdflatex example_article_permutations
pdflatex example_article_permutations
