#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/permutations/vignettes/* .
./tragularize permutations.Rnw 
R CMD Sweave example_article_permutations.Rnw
latexmk -pdf example_article_permutations.tex
