#! /bin/bash

## remember you have to execute submod once

cp ./quadform/inst/quadform_tragula.Rnw ./example_article_quadform.Rnw
cp ./quadform/inst/quadform.bib .
cp ./quadform/man/figures/quadform.png .
R CMD Sweave example_article_quadform.Rnw
pdflatex example_article_quadform
bibtex example_article_quadform
pdflatex example_article_quadform
pdflatex example_article_quadform
