#! /bin/bash

base_dir=~/rstudoi

cp ${base_dir}/stokes/inst/stokes_tragula.Rnw ./stokes.Rnw
cp ${base_dir}/stokes/vignettes/stokes.bib .
cp ${base_dir}/stokes/man/figures/stokes.png .
./tragularize stokes.Rnw
R CMD Sweave example_article_stokes.Rnw 
pdflatex example_article_stokes
bibtex   example_article_stokes
pdflatex example_article_stokes
pdflatex example_article_stokes
