#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/stokes/inst/stokes_tragula.Rnw ./stokes.Rnw
cp ${base_dir}/stokes/vignettes/stokes.bib .
cp ${base_dir}/stokes/man/figures/stokes.png .
./tragularize stokes.Rnw
R CMD Sweave example_article_stokes.Rnw 
latexmk -pdf example_article_stokes.tex
