#! /bin/bash

## Executing this file adds submodules.  The submodules are R package
## directories.  Shell scripts like 'lorentzmaker' use the package
## vignettes to and create example Tragula articles with names like
## "example_article_lorentz.pdf".

## You only need to execute this file once.

if [ ! -d "knotR" ]; then 
    git submodule add https://github.com/RobinHankin/knotR.git knotR
fi

if [ ! -d "lorentz" ]; then 
    git submodule add https://github.com/RobinHankin/lorentz.git lorentz
fi

if [ ! -d "permutations" ]; then
    git submodule add https://github.com/RobinHankin/permutations.git permutations
fi

if [ ! -d "spray" ]; then
    git submodule add https://github.com/RobinHankin/spray.git spray
fi

if [ ! -d "freegroup" ]; then
    git submodule add https://github.com/RobinHankin/freegroup.git freegroup
fi




