#! /bin/bash

## Executing this file adds clones a few other repos.  Most of the
## clones are R package directories.  Shell scripts like
## 'lorentzmaker' use the package vignettes to and create example
## Tragula articles with names like "example_article_lorentz.pdf".
## The crinkled arc one is an exception as this is not an R package.

## You only need to execute this file once.



rm -rf knotR lorentz permutations spray freegroup crinkled_arc

git clone https://github.com/RobinHankin/lorentz
git clone https://github.com/RobinHankin/permutations 
git clone https://github.com/RobinHankin/spray 
git clone https://github.com/RobinHankin/freegroup
git clone https://github.com/RobinHankin/crinkled_arc
git clone https://github.com/RobinHankin/weyl
