#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/inst/vfunc_tragula.Rnw ./example_article_vfunc.Rnw
cp ${base_dir}/vignettes/vfunc.bib .
cp ${base_dir}/man/figures/vfunc.png .
R CMD Sweave example_article_vfunc.Rnw
pdflatex example_article_vfunc
bibtex example_article_vfunc
pdflatex example_article_vfunc
pdflatex example_article_vfunc
