#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/vfunc/inst/vfunc_tragula.Rnw ./example_article_vfunc.Rnw
cp ${base_dir}/vfunc/vignettes/vfunc.bib .
cp ${base_dir}/vfunc/man/figures/vfunc.png .
R CMD Sweave example_article_vfunc.Rnw
latexmk -pdf example_article_vfunc.tex
