#! /bin/bash

## remember you have to execute submod once

cp ./weyl/inst/weyl_tragula.Rnw ./example_article_weyl.Rnw
cp ./weyl/inst/weyl.bib .
cp ./weyl/man/figures/weyl.png .
R CMD Sweave example_article_weyl.Rnw
pdflatex example_article_weyl
bibtex example_article_weyl
pdflatex example_article_weyl
pdflatex example_article_weyl
