#! /bin/bash

base_dir=~/rstudio

cp ${base_dir}/weyl/inst/weyl_tragula.Rnw ./example_article_weyl.Rnw
cp ${base_dir}/weyl/inst/weyl.bib .
cp ${base_dir}/weyl/man/figures/weyl.png .
R CMD Sweave example_article_weyl.Rnw
latexmk -pdf example_article_weyl.tex
