name: build guidelines.zip

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*'  # trigger on version tags like v1.0, v1.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra texlive-luatex texlive-xetex

    - name: Build guidelines.pdf
      run: |
        R CMD Sweave guidelines.Rnw
        pdflatex guidelines
        bibtex guidelines
        pdflatex guidelines
        pdflatex guidelines

    - name: Create guidelines.zip
      run: |
        ZIPFILE="guidelines.zip"
        zip -r "$ZIPFILE" \
          guidelines.pdf guidelines.Rnw guidelines.tex template.bib \
          tragula.bst tragula.cls tragula_knot.pdf tragula_word.pdf ORCID_iD.pdf
        echo "ZIPFILE=$ZIPFILE" >> $GITHUB_ENV

    - name: Upload zip as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: guidelines-zip
        path: ${{ env.ZIPFILE}}
