name: build guidelines.zip

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*'  # trigger on version tags like v1.0, v1.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-bibtex-extra \
          texlive-luatex \
          texlive-xetex \
          latexmk

    - name: Build guidelines.pdf
      run: bash scripts/guidelinesmaker

    - name: Create guidelines.zip
      run: |
        zip -r guidelines.zip \
          guidelines.pdf guidelines.Rnw guidelines.tex template.bib \
          tragula.bst tragula.cls tragula_knot.pdf tragula_word.pdf ORCID_iD.pdf

    - name: Upload zip as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: guidelines-files
        path: |
          guidelines.zip
          guidelines.pdf