name: Build example_article_quadform.pdf

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-bibtex-extra \
          texlive-luatex \
          texlive-xetex \
          texlive-fonts-extra

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Build quadform example
      run: |
        git clone https://github.com/robinhankin/quadform.git
        cp quadform/inst/quadform_tragula.Rnw ./example_article_quadform.Rnw
        cp quadform/inst/quadform.bib .
        cp /quadform/man/figures/quadform.png .
        R CMD Sweave example_article_quadform.Rnw
        pdflatex example_article_quadform
        bibtex example_article_quadform
        pdflatex example_article_quadform
        pdflatex example_article_quadform

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: example-quadform
        path: example_article_quadform.pdf
